### ISSUE TITLE
입력 데이터 검증 annotation vs service

### ISSUE THREAD

**Issue by kyungrae** [codesquad-member-2020/signup-2#6]
스프링 부트에서 입력 검증을 어떻게 하는지 알아보자.

**Comment by beemiel** [comment]
이건 어떤 이슈인가요?

**Comment by kyungrae** [comment]
지금 클라이언트에서 제공해준 데이터가 유효한 데이터인지 확인하지 않고 있잖아요.

원래는 서버에서도 클라이언트가 제공한 데이터가 유효한 데이터인지 확인하고 데이터베이스에 저장하는 과정이 필요해요. 그런데 데이터를 검증하는 방법을 어떻게 할까 고민했었어요.

스프링을 보니깐 valid 어노테이션이 존재해서 이 방법으로 구현할까 아니면 서비스 레이어서 검증을할까 고민하는 이슈입니다.
